better token scripts
in the docker entrypoint script, if /root/vault_token doesn't exist,
just try to create it when the container is run.

better error reporting for every other script, too!

diff --git a/docker/development/get-secret-id b/docker/development/get-secret-id
--- a/docker/development/get-secret-id
+++ b/docker/development/get-secret-id
@@ -3,4 +3,15 @@
 UNWRAP_URL="http://flowercluster:8200/v1/sys/wrapping/unwrap"
 SECRET_TOKEN=$1
 
-curl -X POST -H "X-Vault-Token: ${SECRET_TOKEN}" $UNWRAP_URL 2>/dev/null | jq -r '.data.secret_id'
+RESPONSE=$(curl -X POST -H "X-Vault-Token: ${SECRET_TOKEN}" $UNWRAP_URL 2>/dev/null)
+
+TOKEN=$(jq -r '.data.secret_id' <<< "$RESPONSE")
+
+if [[ $TOKEN == 'null' ]]; then
+  echo "failed to fetch SecretID:"
+  jq '.' <<< "$RESOPNSE"
+
+  exit 1
+else
+  echo $TOKEN
+fi
diff --git a/docker/development/get-token b/docker/development/get-token
--- a/docker/development/get-token
+++ b/docker/development/get-token
@@ -6,9 +6,17 @@ ROLE_ID=$(cat /root/role-id)
 SECRET_ID=$1
 
 DATA=$(printf '{"role_id":"%s","secret_id":"%s"}' $ROLE_ID $SECRET_ID)
+RESPONSE=$(curl -q -X POST -d @- $AUTH_URL 2>/dev/null <<< "$DATA")
 
-RESPONSE=$(echo $DATA | curl -q -X POST -d @- $AUTH_URL 2>/dev/null)
+TOKEN=$(jq -r '.auth.client_token' <<< "$RESPONSE")
 
-echo $RESPONSE | jq -r '.auth.client_token' | tee /root/vault_token
+if [[ $TOKEN == 'null' ]]; then
+  echo "failed to fetch AppRole token:"
+  jq '.' <<< "$RESPONSE"
 
-chmod 600 /root/vault_token
+  exit 1
+else
+  echo "successfully fetched AppRole token!"
+  echo $TOKEN > /root/vault_token && chmod 600 /root/vault_token
+fi
+
